#!/usr/bin/env bash
# gen_uvm_sizes.sh — regenerate uvm_sizes.h from the vendored open driver headers.
#
# WHY THIS EXISTS (measured 2026-08-10, and it is the Phase-1b instrument bug):
# nvidia-uvm ioctl numbers are RAW small integers -- `#define UVM_IOCTL_BASE(i) i`
# (research_clones/ogkm-580.159.04/kernel-open/nvidia-uvm/uvm_ioctl.h:40) -- so
# _IOC_SIZE() of a UVM request is MEANINGLESS. UVM_INITIALIZE is the magic constant
# 0x30000001, whose bits decode as "size = 12288"; a shim that trusts _IOC_SIZE reads
# ~12 KB (clamped to whatever its buffer is) of unrelated stack and reports it as the
# ioctl parameter. That memory differs between two runs of the SAME binary, so it
# manufactures divergence out of nothing. Sizes must come from the headers.
#
# Usage: ./gen_uvm_sizes.sh [path/to/ogkm] > uvm_sizes.h
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OGKM="${1:-$HERE/../../../research_clones/ogkm-580.159.04}"
UVMDIR="$OGKM/kernel-open/nvidia-uvm"
[ -f "$UVMDIR/uvm_ioctl.h" ] || { echo "no uvm_ioctl.h under $UVMDIR" >&2; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# name -> ioctl number, from `#define UVM_FOO UVM_IOCTL_BASE(n)`
grep -oE '^#define[[:space:]]+UVM_[A-Z0-9_]+[[:space:]]+UVM_IOCTL_BASE\([0-9]+\)' \
    "$UVMDIR/uvm_ioctl.h" \
  | sed -E 's/^#define[[:space:]]+(UVM_[A-Z0-9_]+)[[:space:]]+UVM_IOCTL_BASE\(([0-9]+)\)/\1 \2/' \
  | sort -u > "$TMP/nums"

{
  echo '#include <stdio.h>'
  echo '#include "uvm_ioctl.h"'
  [ -f "$UVMDIR/uvm_linux_ioctl.h" ] && echo '#include "uvm_linux_ioctl.h"'
  echo 'int main(void){'
  while read -r name num; do
      # emit only when the matching *_PARAMS typedef really exists
      if grep -q "} ${name}_PARAMS;" "$UVMDIR/uvm_ioctl.h"; then
          echo "  printf(\"  { %u, %u, \\\"%s\\\" },\\n\", (unsigned)$num, (unsigned)sizeof(${name}_PARAMS), \"${name#UVM_}\");"
      else
          echo "  printf(\"  { %u, 0, \\\"%s\\\" },\\n\", (unsigned)$num, \"${name#UVM_}\");"
      fi
  done < "$TMP/nums"
  # the two magic-constant ioctls live in uvm_linux_ioctl.h
  echo '#ifdef UVM_INITIALIZE'
  echo '  printf("  { 0x%x, %u, \"INITIALIZE\" },\n", (unsigned)UVM_INITIALIZE, (unsigned)sizeof(UVM_INITIALIZE_PARAMS));'
  echo '#endif'
  echo '#ifdef UVM_DEINITIALIZE'
  echo '  printf("  { 0x%x, 0, \"DEINITIALIZE\" },\n", (unsigned)UVM_DEINITIALIZE);'
  echo '#endif'
  echo '  return 0;'
  echo '}'
} > "$TMP/g.c"

INCS="-I$UVMDIR -I$OGKM/kernel-open/common/inc -I$OGKM/src/common/inc"
PRE=""

# Some *_PARAMS typedefs exist only inside #if defined(WIN32) blocks. There is no
# preprocessor test for "does this typedef exist", so drop them by iterated compile:
# any name the compiler reports undeclared is removed and we try again.
for _round in 1 2 3 4 5 6 7 8 9 10; do
    # LC_ALL=C so gcc quotes identifiers with ASCII ' and not U+2018/U+2019
    if LC_ALL=C cc -o "$TMP/g" "$TMP/g.c" $INCS $PRE 2>"$TMP/e"; then break; fi
    bad="$(grep -oE "'UVM_[A-Z0-9_]+_PARAMS'" "$TMP/e" | tr -d "'" | sort -u || true)"
    if [ -z "$bad" ]; then cat "$TMP/e" >&2; exit 1; fi
    for b in $bad; do
        sed -i "s/(unsigned)sizeof($b)/(unsigned)0/" "$TMP/g.c"
        echo "note: no $b typedef in this driver -- size recorded as 0 (unmeasured)" >&2
    done
done
[ -x "$TMP/g" ] || { cat "$TMP/e" >&2; exit 1; }

echo "/* GENERATED by gen_uvm_sizes.sh from $(basename "$OGKM") -- do not edit. */"
echo "/* nvidia-uvm ioctl numbers are raw ints (uvm_ioctl.h:40); _IOC_SIZE is meaningless. */"
echo "struct uvm_sz { unsigned nr; unsigned size; const char *name; };"
echo "static const struct uvm_sz uvm_sizes[] = {"
"$TMP/g"
echo "};"
