/*
 * nvdiff_shim.c — LD_PRELOAD ioctl/mmap recorder for /dev/nvidia* , JSONL output.
 *
 * Purpose: the *capture half* of the standing host<->guest differential oracle.
 * It records, for every ioctl issued against an NVIDIA device node:
 *   - the ordering (a global atomic sequence number) and the issuing thread
 *   - the ioctl request word, fully decoded into dir/type/nr/size
 *   - the RAW ioctl header bytes, BEFORE and AFTER the call (so [OUT] fields are visible)
 *   - for escapes that carry an out-of-line parameter block (RM_CONTROL, RM_ALLOC):
 *     the parameter POINTER, the driver-declared parameter SIZE, and the parameter
 *     BYTES before and after the call
 *   - the return value and errno
 *
 * Design rules, each of which exists because of a measured failure in this project:
 *   - ALL decoding is done by nvdiff.py, never here. The capture must be re-decodable
 *     without re-running the workload.
 *   - Parameter bytes are read with process_vm_readv() on our own pid, so a bogus or
 *     unmapped pointer yields a short read instead of a SIGSEGV inside the tracee.
 *   - A truncated buffer is flagged ("trunc":true), never silently shortened: an empty
 *     or short capture must never be mistaken for evidence of emptiness.
 *   - Records are assembled in a thread-local buffer and emitted with ONE write() to an
 *     O_APPEND fd, so multi-threaded libcuda cannot interleave half-records.
 *
 * Build:  cc -shared -fPIC -O2 -o nvdiff_shim.so nvdiff_shim.c -ldl -lpthread
 * Use:    NVDIFF_OUT=/path/trace.jsonl LD_PRELOAD=./nvdiff_shim.so ./prog
 *
 * Env:
 *   NVDIFF_OUT     output path (default: ./nvdiff.jsonl)
 *   NVDIFF_MAXBUF  max parameter bytes captured per side (default 65536)
 *   NVDIFF_MMAP    1 = also record mmap/munmap of nvidia fds (default 1)
 *   NVDIFF_PROBE   bytes to read when the size is UNKNOWN (default 0 -- see below)
 *
 * ★ Why NVDIFF_PROBE defaults to 0, measured 2026-08-10.
 * nvidia-uvm ioctl numbers are RAW integers (`#define UVM_IOCTL_BASE(i) i`,
 * ogkm-580.159.04/kernel-open/nvidia-uvm/uvm_ioctl.h:40) and UVM_INITIALIZE is the
 * magic constant 0x30000001. _IOC_SIZE(0x30000001) = 12288, but the real struct
 * UVM_INITIALIZE_PARAMS is 16 bytes. A first cut of this shim trusted _IOC_SIZE and
 * so recorded 512 bytes of unrelated stack as "the parameter"; that memory differs
 * between two runs of the SAME binary, and it alone produced 2672 spurious
 * divergences in the host-vs-host control. Sizes for /dev/nvidia-uvm* therefore come
 * from uvm_sizes.h (generated from the driver headers). When a size is genuinely
 * unknown we record ZERO bytes and flag it -- unmeasured, never guessed.
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <stdint.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <dlfcn.h>
#include <sys/uio.h>
#include <sys/mman.h>
#include <sys/syscall.h>
#include <sys/ioctl.h>

#ifndef _IOC_SIZE
#include <asm/ioctl.h>
#endif

#define NV_IOCTL_MAGIC 'F'

#include "uvm_sizes.h"   /* generated by gen_uvm_sizes.sh from the open driver headers */

static int   (*r_ioctl)(int, unsigned long, void *);
static void *(*r_mmap)(void *, size_t, int, int, int, off_t);
static int   (*r_munmap)(void *, size_t);

static int      g_fd = -1;
/* ★★★ 65536, not 8192 — measured 2026-08-12, boot w274b_pin.
 * At 8192 the recorder truncated 18/18 guest and 25/25 host
 * UVM_MAP_EXTERNAL_ALLOCATION records — sizeof(PARAMS) = 9264, the LARGEST struct in
 * uvm_sizes.h, so the cap cut exactly the call the divergence lands on and every value
 * diff on it was computed over a partial buffer. Three orchestration scripts already
 * pinned 65536 in their own env; the DEFAULT was the one that was wrong, so a caller
 * driving nvd_capture.sh directly (as the w274 hook did) silently got the truncated
 * answer. A correct value carried by every caller except the default is not a default. */
static unsigned g_maxbuf = 65536;
static unsigned g_probe  = 0;
static int      g_mmap   = 1;
static uint64_t g_seq    = 0;   /* atomic */
static pid_t    g_pid;

/* fd -> device-node basename cache. NVIDIA opens few fds; a flat table is enough. */
#define FDCACHE 4096
static char  g_fdname[FDCACHE][32];
static char  g_fdknown[FDCACHE];   /* 0 unknown, 1 nvidia, 2 not-nvidia */

static void nvdiff_init(void)
{
    const char *p;
    if (g_fd >= 0) return;
    r_ioctl  = dlsym(RTLD_NEXT, "ioctl");
    r_mmap   = dlsym(RTLD_NEXT, "mmap");
    r_munmap = dlsym(RTLD_NEXT, "munmap");
    g_pid = getpid();
    p = getenv("NVDIFF_MAXBUF"); if (p) g_maxbuf = (unsigned)strtoul(p, NULL, 0);
    p = getenv("NVDIFF_PROBE");  if (p) g_probe  = (unsigned)strtoul(p, NULL, 0);
    p = getenv("NVDIFF_MMAP");   if (p) g_mmap   = atoi(p);
    p = getenv("NVDIFF_OUT");    if (!p) p = "./nvdiff.jsonl";
    g_fd = open(p, O_WRONLY | O_CREAT | O_APPEND | O_CLOEXEC, 0644);
    if (g_fd < 0) g_fd = 2;
}

/* Return 1 and fill name if fd is an /dev/nvidia* node. */
static int fd_is_nvidia(int fd, const char **name)
{
    char link[64], path[256];
    ssize_t n;
    const char *base;

    if (fd < 0) return 0;
    if (fd < FDCACHE && g_fdknown[fd]) {
        *name = g_fdname[fd];
        return g_fdknown[fd] == 1;
    }
    snprintf(link, sizeof(link), "/proc/self/fd/%d", fd);
    n = readlink(link, path, sizeof(path) - 1);
    if (n < 0) return 0;
    path[n] = 0;
    if (strncmp(path, "/dev/nvidia", 11) != 0) {
        if (fd < FDCACHE) g_fdknown[fd] = 2;
        return 0;
    }
    base = path + 5;                       /* skip "/dev/" */
    if (fd < FDCACHE) {
        snprintf(g_fdname[fd], sizeof(g_fdname[fd]), "%s", base);
        g_fdknown[fd] = 1;
        *name = g_fdname[fd];
    } else {
        static __thread char tmp[32];
        snprintf(tmp, sizeof(tmp), "%s", base);
        *name = tmp;
    }
    return 1;
}

/* close() must invalidate the cache or an fd number can be reused for another node. */
int close(int fd)
{
    static int (*r_close)(int);
    if (!r_close) r_close = dlsym(RTLD_NEXT, "close");
    if (fd >= 0 && fd < FDCACHE) g_fdknown[fd] = 0;
    return r_close(fd);
}

/* Safe self-read: never faults, returns bytes actually read. */
static size_t safe_read(const void *addr, void *dst, size_t len)
{
    struct iovec l = { dst, len }, rmt = { (void *)addr, len };
    ssize_t n;
    if (!addr || !len) return 0;
    n = process_vm_readv(g_pid, &l, 1, &rmt, 1, 0);
    if (n < 0) return 0;
    return (size_t)n;
}

static const char hexd[] = "0123456789abcdef";
static size_t put_hex(char *out, const unsigned char *b, size_t n)
{
    size_t i;
    for (i = 0; i < n; i++) { out[2*i] = hexd[b[i] >> 4]; out[2*i+1] = hexd[b[i] & 15]; }
    return 2 * n;
}

/*
 * Where the out-of-line parameter block lives, per escape.
 * NVOS54 (RM_CONTROL): params @16, paramsSize @24   -- nvos.h:2238
 * NVOS21 (RM_ALLOC, 32B ioctl): pAllocParms @16, paramsSize @24 -- nvos.h:471
 * NVOS64 (RM_ALLOC, 48B ioctl): pAllocParms @16, paramsSize @32 -- nvos.h:488
 * Everything else: header only (self-contained), decoded by nvdiff.py.
 */
static int param_slot(unsigned nr, unsigned iocsize, unsigned *po, unsigned *so)
{
    if (nr == 0x2A) { *po = 16; *so = 24; return 1; }
    if (nr == 0x2B) { *po = 16; *so = (iocsize >= 48) ? 32 : 24; return 1; }
    return 0;
}

static int dev_is_uvm(const char *dev)
{
    return strncmp(dev, "nvidia-uvm", 10) == 0;
}

/*
 * How many bytes of *argp are actually the ioctl argument?
 *   "ioc" -- /dev/nvidia{ctl,N}: the request word is a real _IOC() encoding.
 *   "tbl" -- /dev/nvidia-uvm*:   the request word is a raw integer, so the size can
 *            only come from the driver headers (uvm_sizes.h).
 *   "none"-- unknown. We read ZERO bytes rather than invent a window.
 */
static unsigned arg_len(const char *dev, unsigned long req, unsigned iocsize,
                        const char **src)
{
    size_t i;
    if (dev_is_uvm(dev)) {
        for (i = 0; i < sizeof(uvm_sizes) / sizeof(uvm_sizes[0]); i++) {
            if (uvm_sizes[i].nr == (unsigned)req) {
                if (uvm_sizes[i].size) { *src = "tbl"; return uvm_sizes[i].size; }
                break;
            }
        }
        *src = "none";
        return g_probe;
    }
    if (iocsize) { *src = "ioc"; return iocsize; }
    *src = "none";
    return g_probe;
}

static const char *uvm_name(unsigned long req)
{
    size_t i;
    for (i = 0; i < sizeof(uvm_sizes) / sizeof(uvm_sizes[0]); i++)
        if (uvm_sizes[i].nr == (unsigned)req) return uvm_sizes[i].name;
    return NULL;
}

int ioctl(int fd, unsigned long req, ...)
{
    va_list ap;
    void *arg;
    const char *dev = NULL;
    unsigned nr, ty, dir, iocsize, hlen, plen_pre = 0, plen_post = 0;
    unsigned po = 0, so = 0, has_params = 0, declared = 0;
    uint64_t pptr = 0, seq;
    unsigned char *hdr_pre = NULL, *hdr_post = NULL;
    unsigned char *pbuf_pre = NULL, *pbuf_post = NULL;
    size_t got_hdr_pre = 0, got_hdr_post = 0;
    const char *lensrc = "none";
    const char *uname_ = NULL;
    int rc, saved_errno;
    char *rec;
    size_t o = 0, cap;
    int trunc = 0;

    va_start(ap, req);
    arg = va_arg(ap, void *);
    va_end(ap);

    if (!r_ioctl) nvdiff_init();

    ty = (unsigned)((req >> 8) & 0xff);
    nr = (unsigned)(req & 0xff);
    dir = (unsigned)_IOC_DIR(req);
    iocsize = (unsigned)_IOC_SIZE(req);

    if (!fd_is_nvidia(fd, &dev))
        return r_ioctl(fd, req, arg);

    hlen = arg_len(dev, req, iocsize, &lensrc);
    uname_ = dev_is_uvm(dev) ? uvm_name(req) : NULL;
    /* ★ A "tbl" length is NOT externally derived: it is a compile-time sizeof(*_PARAMS)
     * emitted from the open-driver headers by gen_uvm_sizes.sh, bounded by construction
     * (max 9264 = MAP_EXTERNAL_ALLOCATION) and already trusted enough to be the ONLY
     * reason this shim is not reading _IOC_SIZE garbage. Capping it can therefore only
     * destroy known-good bytes, never bound an unknown read. "ioc" lengths and the RM
     * `declared` params length below stay capped — those come from the caller. */
    if (hlen > g_maxbuf && strcmp(lensrc, "tbl") != 0) { hlen = g_maxbuf; trunc |= 1; }
    if (hlen) {
        hdr_pre  = malloc(hlen);
        hdr_post = malloc(hlen);
        if (hdr_pre) got_hdr_pre = safe_read(arg, hdr_pre, hlen);
    }

    if (ty == NV_IOCTL_MAGIC && !dev_is_uvm(dev) &&
        param_slot(nr, iocsize, &po, &so) && got_hdr_pre >= so + 4) {
        memcpy(&pptr, hdr_pre + po, 8);
        memcpy(&declared, hdr_pre + so, 4);
        has_params = 1;
        plen_pre = declared > g_maxbuf ? g_maxbuf : declared;
        if (declared > g_maxbuf) trunc |= 2;
        if (plen_pre) {
            pbuf_pre  = malloc(plen_pre);
            pbuf_post = malloc(plen_pre);
            if (pbuf_pre) plen_pre = (unsigned)safe_read((void *)(uintptr_t)pptr, pbuf_pre, plen_pre);
        }
    }

    seq = __atomic_fetch_add(&g_seq, 1, __ATOMIC_RELAXED);
    rc = r_ioctl(fd, req, arg);
    saved_errno = errno;

    if (hdr_post && hlen) got_hdr_post = safe_read(arg, hdr_post, hlen);
    if (has_params && pbuf_post && plen_pre)
        plen_post = (unsigned)safe_read((void *)(uintptr_t)pptr, pbuf_post, plen_pre);

    cap = 512 + 4 * (got_hdr_pre + got_hdr_post) + 4 * (plen_pre + plen_post) + 256;
    rec = malloc(cap);
    if (rec) {
        o += (size_t)snprintf(rec + o, cap - o,
            "{\"i\":%llu,\"t\":\"ioctl\",\"tid\":%ld,\"dev\":\"%s\",\"req\":\"0x%lx\","
            "\"dir\":%u,\"type\":%u,\"nr\":%u,\"iocsize\":%u,\"rc\":%d,\"errno\":%d,"
            "\"argp\":\"0x%llx\"",
            (unsigned long long)seq, (long)syscall(SYS_gettid), dev, req,
            dir, ty, nr, iocsize, rc, rc < 0 ? saved_errno : 0,
            (unsigned long long)(uintptr_t)arg);
        o += (size_t)snprintf(rec + o, cap - o, ",\"hlen\":%u,\"lensrc\":\"%s\"",
                              (unsigned)got_hdr_pre, lensrc);
        if (uname_) o += (size_t)snprintf(rec + o, cap - o, ",\"uvm\":\"%s\"", uname_);
        o += (size_t)snprintf(rec + o, cap - o, ",\"hpre\":\"");
        if (hdr_pre) o += put_hex(rec + o, hdr_pre, got_hdr_pre);
        o += (size_t)snprintf(rec + o, cap - o, "\",\"hpost\":\"");
        if (hdr_post) o += put_hex(rec + o, hdr_post, got_hdr_post);
        o += (size_t)snprintf(rec + o, cap - o, "\"");
        if (has_params) {
            o += (size_t)snprintf(rec + o, cap - o,
                ",\"pptr\":\"0x%llx\",\"psize\":%u,\"pgot\":%u",
                (unsigned long long)pptr, declared, plen_pre);
            o += (size_t)snprintf(rec + o, cap - o, ",\"ppre\":\"");
            if (pbuf_pre) o += put_hex(rec + o, pbuf_pre, plen_pre);
            o += (size_t)snprintf(rec + o, cap - o, "\",\"ppost\":\"");
            if (pbuf_post) o += put_hex(rec + o, pbuf_post, plen_post);
            o += (size_t)snprintf(rec + o, cap - o, "\"");
        }
        if (trunc) o += (size_t)snprintf(rec + o, cap - o, ",\"trunc\":%d", trunc);
        o += (size_t)snprintf(rec + o, cap - o, "}\n");
        if (write(g_fd, rec, o) < 0) { /* nothing useful to do */ }
        free(rec);
    }
    free(hdr_pre);
    free(hdr_post);
    free(pbuf_pre);
    free(pbuf_post);
    errno = saved_errno;
    return rc;
}

void *mmap(void *addr, size_t len, int prot, int flags, int fd, off_t off)
{
    const char *dev = NULL;
    void *r;
    char rec[256];
    int n;

    if (!r_mmap) nvdiff_init();
    r = r_mmap(addr, len, prot, flags, fd, off);
    if (g_mmap && fd_is_nvidia(fd, &dev)) {
        uint64_t seq = __atomic_fetch_add(&g_seq, 1, __ATOMIC_RELAXED);
        n = snprintf(rec, sizeof(rec),
            "{\"i\":%llu,\"t\":\"mmap\",\"tid\":%ld,\"dev\":\"%s\",\"len\":%llu,"
            "\"prot\":%d,\"flags\":%d,\"off\":\"0x%llx\",\"ret\":\"0x%llx\"}\n",
            (unsigned long long)seq, (long)syscall(SYS_gettid), dev,
            (unsigned long long)len, prot, flags,
            (unsigned long long)off, (unsigned long long)(uintptr_t)r);
        if (write(g_fd, rec, (size_t)n) < 0) { }
    }
    return r;
}
