obj-m := nvkvm-guest.o

nvkvm-guest-objs := nvkvm_main.o \
                    nvkvm_ioctl.o \
                    nvkvm_virtio.o \
                    nvkvm_mmap.o \
                    nvkvm_session.o \
                    nvkvm_hostfile.o

ccflags-y := -I$(src)/.. -I$(src)/../..
