#!/usr/bin/env python3
# mode2_gen_compute_ctrls.py — convert captured GA106 cuInit RM-control responses
# (docs/research/captures/ga106_cuinit_dump.log; lines "CC cmd=0xXXX sz=N st=0xS : <hex>")
# into src/qemu/mode2_compute_ctrls_ga106.h:
#   - byte blobs for blob-style controls (GR_FS_INFO, ENGINES, CLASSLIST, MC_ARCH,
#     CAPS_V2, SM_ORDER, masks)
#   - {index,value} maps for the inline index-list controls (GPU_GET_INFO_V2,
#     FB_GET_INFO_V2) merged across all captured requests (covers every phase)
# All values are real RTX 3060 / GA106 / 580.159.04 ground truth.
import re, sys, collections

LOG = "docs/research/captures/ga106_cuinit_dump.log"
OUT = "src/qemu/mode2_compute_ctrls_ga106.h"

# index-list controls: {count(u32), then count*{index(u32),value(u32)}}
INDEX_LIST = {0x20800102: "gpu_get_info_v2", 0x20801303: "fb_get_info_v2"}
# blob controls: replay verbatim (keep the LARGEST capture seen)
BLOBS = {
    0x20803801: "grmgr_gr_fs_info", 0x20800170: "gpu_get_engines_v2",
    0x00800292: "gpu_get_classlist_v2", 0x20801701: "mc_get_arch_info",
    0x20801227: "gr_get_caps_v2", 0x2080121b: "gr_get_global_sm_order",
}

def parse(line):
    m = re.search(r"cmd=0x([0-9a-fA-F]+)\s+sz=(\d+)\s+st=0x([0-9a-fA-F]+)\s*:\s*(.*)", line)
    if not m: return None
    cmd = int(m.group(1), 16); sz = int(m.group(2)); st = int(m.group(3), 16)
    b = bytes(int(x, 16) for x in m.group(4).split())
    return cmd, sz, st, b

blobs = {}                              # cmd -> (status, bytes) largest
imaps = collections.defaultdict(dict)   # cmd -> {index: value}
for line in open(LOG):
    p = parse(line)
    if not p: continue
    cmd, sz, st, b = p
    if cmd in INDEX_LIST:
        if len(b) < 4: continue
        n = int.from_bytes(b[0:4], "little")
        for i in range(n):
            off = 4 + i*8
            if off+8 > len(b): break
            idx = int.from_bytes(b[off:off+4], "little")
            val = int.from_bytes(b[off+4:off+8], "little")
            imaps[cmd][idx] = val
    elif cmd in BLOBS:
        if cmd not in blobs or len(b) > len(blobs[cmd][1]):
            blobs[cmd] = (st, b)

def carr(name, b):
    out = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(b), 16):
        out.append("  " + ",".join(f"0x{x:02x}" for x in b[i:i+16]) + ",")
    out.append("};")
    return "\n".join(out)

lines = ["/* mode2_compute_ctrls_ga106.h — GENERATED by tools/mode2_gen_compute_ctrls.py",
         " * from docs/research/captures/ga106_cuinit_dump.log (real RTX 3060/GA106/580).",
         " * cuInit compute-cap RM-control responses: index->value maps + blobs. */",
         "#ifndef MODE2_COMPUTE_CTRLS_GA106_H", "#define MODE2_COMPUTE_CTRLS_GA106_H",
         "typedef struct { unsigned int index; unsigned int value; } nvkvm_idxval_t;", ""]

for cmd, nm in INDEX_LIST.items():
    m = imaps.get(cmd, {})
    lines.append(f"/* 0x{cmd:08x} {nm}: {len(m)} indices (merged across captures) */")
    lines.append(f"static const nvkvm_idxval_t {nm}_map[] = {{")
    for idx in sorted(m):
        lines.append(f"  {{ 0x{idx:x}, 0x{m[idx]:x} }},")
    lines.append("};")
    lines.append(f"#define {nm.upper()}_MAP_N {len(m)}")
    lines.append("")

for cmd, nm in BLOBS.items():
    if cmd not in blobs:
        lines.append(f"/* 0x{cmd:08x} {nm}: NOT captured */"); lines.append("")
        continue
    st, b = blobs[cmd]
    lines.append(f"/* 0x{cmd:08x} {nm}: {len(b)}B, status=0x{st:x} */")
    lines.append(carr(f"{nm}_blob", b))
    lines.append(f"#define {nm.upper()}_BLOB_N {len(b)}")
    lines.append("")

lines.append("#endif")
open(OUT, "w").write("\n".join(lines) + "\n")
print(f"wrote {OUT}: {len(imaps)} index-maps, {len(blobs)} blobs")
for cmd in INDEX_LIST: print(f"  0x{cmd:08x} {INDEX_LIST[cmd]}: {len(imaps.get(cmd,{}))} indices")
for cmd in BLOBS: print(f"  0x{cmd:08x} {BLOBS[cmd]}: {len(blobs.get(cmd,(0,b''))[1])}B")
